# Name: Hanan Fared Mohamed Omara , ID =  20398559

# The Answer of Question 4

- I have take some structure from search on internet.


In [1]:
import numpy as np

grid = np.zeros((5,5))
grid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
Y = 0.75  #discount value
for num in range(10): #number of times we will go through the whole grid
  for i in range(5):      #all the rows
    for j in range(5):    #all the columns
      
      up_grid = grid[i-1][j] if i > 0 else 0   #if going up takes us out of the grid then its value be 0
      down_grid = grid[i+1][j] if i < 4 else 0  #if going down takes us out of the grid then its value be 0
      left_grid = grid[i][j-1] if j > 0 else 0  #if going left takes us out of the grid then its value be 0
      right_grid = grid[i][j+1] if j < 4 else 0  #if going right takes us out of the grid then its value be 0

      all_dirs = [up_grid, down_grid, left_grid, right_grid]     

      value=0  
      if i==0 and j==1: # the position of A
        value = 10 + Y*grid[4][1]
      elif i==0 and j==3: # the position of B
        value = 5 + Y*grid[2][3]
      else:
        for direc in all_dirs:
          if direc != 0: 
            value += .25 * (0 + Y*direc)  #if we don't go out of the grid
          else:
            value += .25 * (-1 + Y*grid[i][j]) #if we go out of the grid
        
      grid[i][j] = value   
np.round(grid, 1)


array([[ 2.2,  9.4,  3.3,  5.1,  0.7],
       [ 0.7,  2.2,  1.3,  1.2,  0. ],
       [-0.2,  0.4,  0.3,  0.1, -0.4],
       [-0.7, -0.3, -0.2, -0.3, -0.8],
       [-1.3, -0.8, -0.7, -0.8, -1.3]])

In [6]:
Y = 0.85  #discount value
for num in range(10): #number of times we will go through the whole grid
  for i in range(5):      #all the rows
    for j in range(5):    #all the columns
      
      up_grid = grid[i-1][j] if i > 0 else 0   #if going up takes us out of the grid then its value be 0
      down_grid = grid[i+1][j] if i < 4 else 0  #if going down takes us out of the grid then its value be 0
      left_grid = grid[i][j-1] if j > 0 else 0  #if going left takes us out of the grid then its value be 0
      right_grid = grid[i][j+1] if j < 4 else 0  #if going right takes us out of the grid then its value be 0

      all_dirs = [up_grid, down_grid, left_grid, right_grid]     

      value=0  
      if i==0 and j==1: # the position of A
        value = 10 + Y*grid[4][1]
      elif i==0 and j==3: # the position of B
        value = 5 + Y*grid[2][3]
      else:
        for direc in all_dirs:
          if direc != 0: 
            value += .25 * (0 + Y*direc)  #if we don't go out of the grid
          else:
            value += .25 * (-1 + Y*grid[i][j]) #if we go out of the grid
        
      grid[i][j] = value   
np.round(grid, 1)


array([[ 2.9,  9.1,  4.1,  5.2,  1.2],
       [ 1.2,  2.7,  1.9,  1.7,  0.3],
       [-0.1,  0.6,  0.5,  0.3, -0.4],
       [-0.9, -0.3, -0.3, -0.5, -1. ],
       [-1.6, -1.1, -1. , -1.2, -1.7]])

In [19]:
Y = .9  #discount value
for num in range(10): #number of times we will go through the whole grid
  for i in range(5):      #all the rows
    for j in range(5):    #all the columns
      
      up_grid = grid[i-1][j] if i > 0 else 0   #if going up takes us out of the grid then its value be 0
      down_grid = grid[i+1][j] if i < 4 else 0  #if going down takes us out of the grid then its value be 0
      left_grid = grid[i][j-1] if j > 0 else 0  #if going left takes us out of the grid then its value be 0
      right_grid = grid[i][j+1] if j < 4 else 0  #if going right takes us out of the grid then its value be 0

      all_dirs = [up_grid, down_grid, left_grid, right_grid]     

      value=0  
      if i==0 and j==1: # the position of A
        value = 10 + Y*grid[4][1]
      elif i==0 and j==3: # the position of B
        value = 5 + Y*grid[2][3]
      else:
        for direc in all_dirs:
          if direc != 0: 
            value += .25 * (0 + Y*direc)  #if we don't go out of the grid
          else:
            value += .25 * (-1 + Y*grid[i][j]) #if we go out of the grid
        
      grid[i][j] = value   
np.round(grid, 1)


array([[ 3.3,  8.8,  4.4,  5.3,  1.5],
       [ 1.5,  3. ,  2.3,  1.9,  0.5],
       [ 0.1,  0.7,  0.7,  0.4, -0.4],
       [-1. , -0.4, -0.4, -0.6, -1.2],
       [-1.9, -1.3, -1.2, -1.4, -2. ]])